# NumPy
## #ndarray：n-dimensional array object，即為一般所稱的陣列
## #nfunc：universal function odject，對陣列處理的函數
### 檢視NumPy版本：

In [1]:
import numpy as np
np.__version__

'1.14.5'

### 透過shape更改陣列形狀(3, 4) ---> (4, 3)，不是轉置，是改變軸的大小，且元素個數不變

In [2]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
a.shape = 4, 3
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### 當設定其中一軸為-1，將自動計算軸的長度

In [4]:
a.shape = 2, -1
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [5]:
b = a.reshape(-1, 2)
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [6]:
b[1][1] = 1000000 
# b[1] = 1000000 是修改整個第二列

print(b)
print("\n\n")
print(a)

[[      1       2]
 [      3 1000000]
 [      5       6]
 [      7       8]
 [      9      10]
 [     11      12]]



[[      1       2       3 1000000       5       6]
 [      7       8       9      10      11      12]]


In [7]:
a.dtype

dtype('int32')

### 可在建立陣列時指定元素型別

In [8]:
c_int = np.array([1, 2, 3, 4], dtype = np.int32)
c_float = np.array([1, 2, 3, 4], dtype = np.float)
c_complex = np.array([1, 2, 3, 4], dtype = np.complex)

print(c_int.dtype, c_float.dtype, c_complex.dtype)

int32 float64 complex128


### np.arange(開始值，終值，步進值)

In [9]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### np.linspace(開始值，終值，元素個數，endpoint = True/False)：建立 "等差數列" 的一維陣列，endpoint是否包含終值

In [10]:
np.linspace(0, 20, 5, endpoint=True)

array([ 0.,  5., 10., 15., 20.])

### np.logspace(開始值，終值，元素個數，base = 數值，endpoint = True/False)：建立 "等比數列" 的一維陣列，base可調整底數的值(預設為10)，endpoint是否包含終值

In [11]:
np.logspace(0, 5, 4, base=3, endpoint=False)

array([ 1.        ,  3.94822204, 15.58845727, 61.54669054])

### np.empty()：分配陣列所使用的記憶體，不進行初始化
### np.zeros()，np.ones()：將陣列初始化為0跟1

In [12]:
np.empty((2, 3), np.int)

array([[1630433390, 1735287154,  741353573],
       [ 741356064,  170471968, 1763713024]])

In [13]:
np.zeros(4, np.int)

array([0, 0, 0, 0])

In [14]:
np.ones(4, np.int)

array([1, 1, 1, 1])